=== NormalNotNormal/Web/LabaWeb/src/Book.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT Library (bookcase*)>
<!ELEMENT bookcase  (book*,NumberOfPages?)>
<!ATTLIST bookcase
        number CDATA #REQUIRED
        >

<!ELEMENT book (bookprice, pages)>
<!ATTLIST book
        name CDATA #REQUIRED
        >

<!ELEMENT bookprice EMPTY>
<!ATTLIST bookprice
        price CDATA #REQUIRED
        >

<!ELEMENT pages EMPTY>
<!ATTLIST pages
        quantity CDATA #REQUIRED
        >
<!ELEMENT NumberOfPages (#PCDATA)>

=== NormalNotNormal/Web/LabaWeb3.1/out/production/LabaWeb3.1/XML/Library.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Library SYSTEM "C:\Users\pas20\IdeaProjects\LabaWeb3.1\src\XML\Book.dtd">
    <Library>
        <bookcase number = "0">
            <book name = "Memoirs of a Geisha">
                <bookprice price ="500"/>
                <pages quantity = "350"/>
            </book>
            <book name= "Sherlock Holmes">
                <bookprice price = "625"/>
                <pages quantity = "1150"/>
            </book>
                <book name= "The Running Man">
                <bookprice price = "555"/>
                <pages quantity = "237"/>
            </book>
        </bookcase>
    </Library>
