=== NormalNotNormal/Web/LabaWeb/src/XML/Book.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT Library (bookshelf *)>
<!ELEMENT bookshelf  (book,AmountOfbooks?)>
<!ATTLIST bookshelf
        number CDATA #REQUIRED
        >

<!ELEMENT book (bookprice, bookpages)>
<!ATTLIST book
        name CDATA #REQUIRED
        >

<!ELEMENT bookprice EMPTY>
<!ATTLIST bookprice
        price CDATA #REQUIRED
        >

<!ELEMENT bookpages EMPTY>
<!ATTLIST bookpages
        pages CDATA #REQUIRED
        >
<!ELEMENT AmountOfbooks (#PCDATA)>

=== NormalNotNormal/Web/LabaWeb/out/production/LabaWeb/XML/Library.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Library SYSTEM "C:\Users\pas20\IdeaProjects\LabaWeb\src\XML\Book.dtd">
<Library>
    <bookshelf number = "0">
        <book name = "Memoirs of a Geisha">
            <bookprice price ="500"/>
            <bookpages pages = "350"/>
        </book>
        <book name= "Sherlock Holmes">
            <bookprice price = "625"/>
            <bookpages pages = "1150"/>
        </book>
        <book name= "The Running Man">
            <bookprice price = "555"/>
            <bookpages pages = "237"/>
        </book>
    </bookshelf>
</Library>
